name: AI Trend Research

on:
  schedule:
    # Run daily at 9:00 AM JST (0:00 UTC)
    # - cron: '0 0 * * *'
    - cron: '*/1 * * * *'      
  workflow_dispatch:
    # Allow manual execution

jobs:
  research:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install MCP servers
      run: |
        npm install -g one-search-mcp
        npm install -g @ramidecodes/mcp-server-notion@latest

    - name: Run AI trend research
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
      run: |
        python ai_trend_researcher.py
    
    - name: Commit research results
      run: |
        git config user.email "miyuu112288@gmail.com"
        git config user.name "EmpowerHerDev"
        git add reports/
        git add keywords/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily AI trend research results - $(date '+%Y-%m-%d')"
          git push
        fi
    
    - name: Upload research report
      uses: actions/upload-artifact@v3
      with:
        name: ai-trend-report-${{ github.run_number }}
        path: reports/
        retention-days: 30
